### ISSUE TITLE
Sharepoint does not list files to restore

### ISSUE THREAD

**Issue by murilolang** [nielsengelen/vbo365-rest#80] opened 2020-12-01 15:08 UTC
Hello Niels,
I'm having trouble trying to restore Sharepoint files using API after last upgrade. 
I have 2 organizations in use. One of them is working fine, restores can be done using console and API. 
In the other one, when using console, all the files and folders are shown, and I'm able to restore them.
But when using API, all the folders and subfolders are listed, but the not the files.  I'm using a valid SSL installed certificate.
Investigating API logs, I found some error messages like "The server has rejected the client credentials", "The logon attempt failed" and "Resource cannot be found for current key"
Any tips or ideia what may be the problem?

Regards,
Murilo

**Comment by nielsengelen** [comment] 2020-12-01 16:40
Are you using MFA or basic authentication for the organization which has the issue?

**Comment by murilolang** [comment] 2020-12-01 16:45
Basic authentication for both of them.

**Comment by eazy** [comment] 2020-12-02 09:23
Hi Niels, Hi Murilo,

we are facing the same problem, but not since the last update, we have it > 6 month.
Restore for the most tenants is working with exchange, onedrive and Sharepoint.
Only with one large tenant we have the problem that sharepoint and onedrive isn't working, but Exchnage works.

On the not working tenant the whole interaction is pretty slow, so if I start a restore, the Feedback "Session Started" is not comming up immediately. After pressing OK, it takes a while and than we're getting an PHP Error: "Error creating resource: [message] fopen(https://192.168.123.125:4443/v4/RestoreSessions/4fdcebdc-f5a9-42d2-afb7-31a605a1d0a7/Organization/Sites?offset=0&limit=1000): failed to open stream: HTTP request failed! [file] /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php [line] 324"

maximum_execution_time is set to 1h and shouldn't be the problem.

RESTLog of the Veeam Server [https://pastebin.com/APrZu3xd](https://pastebin.com/APrZu3xd)

If we are using the GUI the tenant works.

Maybe it will help to fix both cases ;-) If you need more information plz let me know.

Thanks

bye
  eazy

**Comment by nielsengelen** [comment] 2020-12-02 10:35
Hi Eazy, on the starting speed of the restore session - I can't do much about this since this is known to be slower in v3 and v4 of VBO. I do have good news that v5 will improve this a lot. It is almost instant from recent testing with the beta. v5 should be released later this year and all the current supported portal features work (well besides this issue :-)). 

From the looks of it, the issue is the limit being 1000 and requesting 1000 items at once. However, v5 also improves this as there are a lot of enhancements to REST API calls in terms of performance. It somewhat looks like v5 is actually the answer here to the problem.

We can do some remote session for the exact flow and when it goes wrong though as this issue looks to be related to larger accounts (something I can't test as I only have accounts of around 200 users). 

It would be great if both of you could drop me an e-mail via niels.engelen@veeam.com and we can pick it up from there (also more secure compared to putting logs on pastebin or other tools. 

Thanks!

**Comment by eazy** [comment] 2020-12-02 10:45
Hi Niels,

thanks for the super fast answer.

I'll drop you an Mail.

The pasted logs have no real accounts and no real domains.

Thanks

**Comment by murilolang** [comment] 2020-12-02 11:22
Hello Niels, thanks for your availability, I'm sending you an e-mail too.

**Comment by nielsengelen** [comment] 2021-01-06 08:37
Follow-up via mail so closing this issue.

**Closed by nielsengelen** 2021-01-06 08:37 UTC
